// Regenerates public/sitemap.xml: main pages + services + published blog
// posts + open job postings. Run from the project root:
//
//   node scripts/generate-sitemap.mjs
//
// Read-only: it selects published/open rows through the public (anon) key in
// .env, the same rows any visitor can read. Re-run and commit whenever a blog
// post is published or a job opens or closes, because Lovable serves this
// static file as /sitemap.xml.
//
// lastmod: a job uses its row's updated_at; a blog post uses created_at,
// because every page view bumps a post's updated_at; for pages it is the
// date of the last git commit touching the page's source (today if the file
// has uncommitted changes).
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

const env = Object.fromEntries(
  readFileSync(".env", "utf8")
    .split(/\r?\n/)
    .map((line) => line.match(/^([A-Z0-9_]+)=["']?(.*?)["']?$/))
    .filter(Boolean)
    .map((m) => [m[1], m[2]]),
);
const SITE = (env.VITE_SITE_URL || "https://zyllotech.com").replace(/\/+$/, "");
const SUPABASE_URL = env.VITE_SUPABASE_URL;
const SUPABASE_KEY = env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Keep equal to src/lib/seo/public-routes.js.
const PAGES = [
  { path: "/", file: "src/pages/Home.jsx", changefreq: "weekly", priority: "1.0" },
  { path: "/about", file: "src/pages/About.jsx", changefreq: "monthly", priority: "0.8" },
  { path: "/services", file: "src/pages/Services.jsx", changefreq: "monthly", priority: "0.9" },
  { path: "/industries", file: "src/pages/Industries.jsx", changefreq: "monthly", priority: "0.7" },
  { path: "/portfolio", file: "src/pages/Portfolio.jsx", changefreq: "weekly", priority: "0.7" },
  { path: "/blog", file: "src/pages/Blog.jsx", changefreq: "weekly", priority: "0.8" },
  { path: "/careers", file: "src/pages/Careers.jsx", changefreq: "weekly", priority: "0.7" },
  { path: "/contact", file: "src/pages/Contact.jsx", changefreq: "yearly", priority: "0.6" },
  { path: "/privacy", file: "src/pages/Privacy.jsx", changefreq: "yearly", priority: "0.2" },
  { path: "/terms", file: "src/pages/Terms.jsx", changefreq: "yearly", priority: "0.2" },
];
const SERVICES_FILE = "src/data/services.js";

const today = new Date().toISOString().slice(0, 10);
function fileDate(file) {
  const dirty = execSync(`git status --porcelain -- "${file}"`).toString().trim();
  if (dirty) return today;
  return execSync(`git log -1 --format=%cs -- "${file}"`).toString().trim() || today;
}

async function rows(table, query) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/${table}?${query}`, {
    headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}` },
  });
  if (!res.ok) throw new Error(`${table}: HTTP ${res.status} ${await res.text()}`);
  return res.json();
}

const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const day = (value) => (value ? new Date(value).toISOString().slice(0, 10) : today);

const serviceSlugs = [...readFileSync(SERVICES_FILE, "utf8").matchAll(/^\s{4}slug: "([^"]+)"/gm)].map((m) => m[1]);
const servicesDate = fileDate(SERVICES_FILE);
const [posts, jobs] = await Promise.all([
  rows("blog_posts", "select=slug,created_at&status=eq.published&order=created_at.desc"),
  rows("job_postings", "select=id,updated_at,created_at&status=eq.open&order=created_at.desc"),
]);

const entries = [
  ...PAGES.map((p) => ({ loc: p.path, lastmod: fileDate(p.file), changefreq: p.changefreq, priority: p.priority })),
  ...serviceSlugs.map((slug) => ({ loc: `/services/${slug}`, lastmod: servicesDate, changefreq: "monthly", priority: "0.7" })),
  ...posts.map((p) => ({ loc: `/blog/${p.slug}`, lastmod: day(p.created_at), changefreq: "monthly", priority: "0.6" })),
  ...jobs.map((j) => ({ loc: `/careers/${j.id}`, lastmod: day(j.updated_at || j.created_at), changefreq: "weekly", priority: "0.5" })),
];

const xml =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!-- Generated by scripts/generate-sitemap.mjs. Re-run after publishing a blog post or opening/closing a job. -->\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  entries
    .map(
      (e) =>
        `  <url><loc>${esc(SITE + e.loc)}</loc><lastmod>${e.lastmod}</lastmod>` +
        `<changefreq>${e.changefreq}</changefreq><priority>${e.priority}</priority></url>`,
    )
    .join("\n") +
  `\n</urlset>\n`;

writeFileSync("public/sitemap.xml", xml);
console.log(
  `public/sitemap.xml: ${entries.length} URLs (${PAGES.length} pages, ${serviceSlugs.length} services, ${posts.length} blog posts, ${jobs.length} jobs)`,
);
